### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by sovlin** [atom/status-bar#44]
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.52.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1300

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1300:34)
  at status-bar-cursor.CursorPositionView.updatePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/cursor-position-view.js:48:73)
  at status-bar-cursor.CursorPositionView.subscribeToActiveTextEditor (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/cursor-position-view.js:39:19)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/cursor-position-view.js:17:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:314:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/src/pane.js:308:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:279:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:379:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:443:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

/cc @atom/core

**Comment by JamesGould123** [comment]
This also occurred for me, after I closed all instances of atom when one took too long to load a large file, and then when I continued to try and open/close other instances, not sure how to replicate, as I believe it was caused by some sort of crash.

**Comment by benogle** [comment]
Looks like you're about 20 versions behind. Please update to the latest version of atom. This may have been fixed.

**Comment by MatthewMueller** [comment]
Looks like this is still happening with the latest, not sure how I ended up in this state though.

**Atom Version**: 0.180.0
**System**: Mac OS X 10.9.5
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.60.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1358

TypeError: Cannot read property 'getBufferPosition' of undefined
    at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1358:34)
    at status-bar-cursor.CursorPositionView.updatePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/cursor-position-view.js:48:73)
    at status-bar-cursor.CursorPositionView.subscribeToActiveTextEditor (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/cursor-position-view.js:39:19)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/cursor-position-view.js:17:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:328:21)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/src/pane.js:322:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:293:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:393:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:457:16)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:685:35)
    at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:729:21)
```

### Commands

```
     -4:39.9 core:save (atom-text-editor.editor)
     -4:31.9 core:backspace (atom-text-editor.editor)
     -4:30.7 core:save (atom-text-editor.editor)
  2x -2:24.9 editor:move-to-beginning-of-word (atom-text-editor.editor)
  6x -2:24.3 core:move-left (atom-text-editor.editor)
  3x -2:22.5 core:save (atom-text-editor.editor)
     -1:24.8 core:copy (atom-text-editor.editor)
     -1:24.1 docblockr:parse-tab (atom-text-editor.editor)
     -1:24.1 snippets:next-tab-stop (atom-text-editor.editor)
     -1:16.5 docblockr:parse-tab (atom-text-editor.editor)
     -1:16.5 snippets:next-tab-stop (atom-text-editor.editor)
     -1:16.5 snippets:expand (atom-text-editor.editor)
     -0:50.8 application:new-file (a.btn-copy-report.icon.icon-clippy)
     -0:50.3 core:paste (atom-text-editor.editor.is-focused)
  2x -0:01.6 core:undo (atom-text-editor.editor.is-focused)
     -0:00.6 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "neutron-ui",
      "advanced-railscasts-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.5.3
advanced-railscasts-syntax, v0.1.8
auto-detect-indentation, v0.3.0
docblockr, v0.5.8
editorconfig, v0.3.0
emmet, v2.3.3
file-icons, v1.4.11
highlight-selected, v0.9.0
neutron-ui, v0.3.0
zentabs, v0.8.2

# Dev
No dev packages
```

**Comment by TouPye** [comment]
1. I tried to create a new file via keybindings (It didn't work,  have no clue why)
2. I closed the "new file" (which was not actually created?) via keybindings and got this error

**Atom Version**: 0.181.0
**System**: Microsoft Windows 8.1
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.60.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\text-editor.js:1358

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\text-editor.js:1358:34)
  at status-bar-cursor.CursorPositionView.updatePosition (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\node_modules\status-bar\lib\cursor-position-view.js:48:73)
  at status-bar-cursor.CursorPositionView.subscribeToActiveTextEditor (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\node_modules\status-bar\lib\cursor-position-view.js:39:19)
  at C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\node_modules\status-bar\lib\cursor-position-view.js:17:24
  at Emitter.module.exports.Emitter.emit (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane.js:328:21)
  at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane.js:322:19)
  at Pane.module.exports.Pane.activateNextItem (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane.js:283:21)
  at Pane.module.exports.Pane.removeItem (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane.js:391:16)
  at Pane.module.exports.Pane.destroyItem (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane.js:457:16)
  at Pane.module.exports.Pane.destroyActiveItem (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\workspace.js:685:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\workspace.js:729:21)
  at atom-workspace.atom.commands.add.core:close (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Pierre\AppData\Local\atom\app-0.181.0\resources\app\src\window-event-handler.js:176:20)

```

### Commands

```
     -0:07.5 application:new-file (atom-text-editor.editor)
     -0:06.4 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "lesscompile",
      "Sublime-Style-Column-Selection"
    ],
    "fileEncoding": "iso885915",
    "themes": [
      "flatland-dark-ui",
      "tomorrow-night-eighties"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.6
color-picker, v1.4.4
column-select, v0.1.0
emmet, v2.3.3
file-icons, v1.4.11
flatland-dark-ui, v0.2.3
linter, v0.11.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
open-last-project, v0.3.1
tomorrow-night-eighties, v0.4.0

# Dev
No dev packages
```

**Comment by tylermumford** [comment]
I encountered this error, then disabled open-last-project and restarted Atom. No more errors after that, and the keybindings are now working correctly.

**Comment by cokelly** [comment]
I can confirm what tylermumford wrote. The error is gone when open-last-project is disabled and Atom is restarted.

**Comment by 50Wliu** [comment]
Looks like this error is caused by packages, so going to close this.

**Comment by MatthewMueller** [comment]
not sure, but I didn't have `open-last-project` installed

**Comment by TouPye** [comment]
I think this error is more a "common thing" that can be triggered in many different ways
